remote_theme: just-the-docs/just-the-docs@main
plugins:
  - jekyll-remote-theme

title: Charts Classifier
description: An image classification API that can classify 28 different types of charts and diagrams

author:
  name: Abir Hassan

favicon_ico: "/images/favicon.ico"

heading_anchors: true

enable_copy_code_button: true

nav_external_links:
  - title: Charts Classifier on GitHub
    url: https://github.com/abir0/Charts-Classifier

color_scheme: nil

callouts_level: quiet
callouts:
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2023 Abir Hassan. Distributed by an <a href=\"https://github.com/abir0/Charts-Classifier/tree/main/LICENSE.txt\">MIT license.</a>"

